# 大佬帮看下日志，不知道哪里出问题了，酸酸**连不上


<i class="pstatus"> 本帖最后由 mhw188 于 2020-10-26 16:29 编辑 </i><br />
<br />
更新下， 服务商封的， 配置什么的并没任何问题<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
服务都启动着，各项参数也正常， 大佬帮看下日志吧，<br />
<br />
<br />
<br /><div class="blockcode"><div id="code_GDg"><ol><li>2020-10-25 21:50:59 INFO&nbsp; &nbsp;&nbsp;&nbsp;server.py:48 current process RLIMIT_NOFILE resource: soft 1024 hard 4096<br /><li>2020-10-25 21:50:59 INFO&nbsp; &nbsp;&nbsp;&nbsp;asyncdns.py:287 black_hostname_list init as : []<br /><li>2020-10-25 21:50:59 INFO&nbsp; &nbsp;&nbsp;&nbsp;asyncdns.py:335 dns server: [('8.8.8.8', 53)]<br /><li>2020-10-25 21:50:59 INFO&nbsp; &nbsp;&nbsp;&nbsp;server.py:108 server start with protocol[auth_sha1_v4] password [110110110] method [aes-256-cfb] obfs [http_simple] obfs_param []<br /><li>2020-10-25 21:50:59 INFO&nbsp; &nbsp;&nbsp;&nbsp;server.py:125 starting server at [::]:34567<br /><li>2020-10-25 21:50:59 INFO&nbsp; &nbsp;&nbsp;&nbsp;server.py:145 starting server at 0.0.0.0:34567<br /><li>2020-10-25 22:31:32 WARNING&nbsp;&nbsp;auth.py:131 obfs auth: duplicate id, someone replay attack<br /><li>2020-10-25 22:31:32 INFO&nbsp; &nbsp;&nbsp;&nbsp;auth.py:355 auth_sha1_v4: auth fail, data 5183955f80296e80f229af000314666f6e74732e676f6f676c65617069732e636f6d01bb<br /><li>2020-10-25 22:31:32 WARNING&nbsp;&nbsp;common.py:250 unsupported addrtype 69, maybe wrong password or encryption method<br /><li>2020-10-25 22:31:32 WARNING&nbsp;&nbsp;tcprelay.py:521 Protocol ERROR, TCP ogn data 47455420*****b4191258c1dec29b597c1bb36eeb885dfde88ab076004b6ddcef1963eaaafe78416e8213a13742b18a701469b90c465affdab29f9138be80c5a3cab63e94dfd519c86e34f663a38d8edc1173b38b6b03b393aea1ddec6d5fda3d6b7b6981975a394e64c3f372717ef9d8fc8087fa49e7cb7d18839573bb200d255a38e8047fb08d352d5000956fc178e0b592a52d3b9322911176e95347b2519a3c634515f0a895ee1c from ::ffff:112.66.99.186:44294 via port 34567 by UID 34567<br /><li>2020-10-25 22:31:32 ERROR&nbsp; &nbsp; tcprelay.py:1097 can not parse header when handling connection from ::ffff:112.66.99.186:44294<br /><li>2020-10-25 23:26:19 WARNING&nbsp;&nbsp;auth.py:125 obfs auth: deprecated id, someone replay attack<br /><li>2020-10-25 23:26:19 INFO&nbsp; &nbsp;&nbsp;&nbsp;auth.py:355 auth_sha1_v4: auth fail, data 6b83955f80296e80fd29af0003176769746875622e6769746875626173736574732e636f6d01bb<br /><li>2020-10-25 23:26:19 WARNING&nbsp;&nbsp;common.py:250 unsupported addrtype 69, maybe wrong password or encryption method<br /><li>2020-10-25 23:26:19 WARNING&nbsp;&nbsp;tcprelay.py:521 Protocol ERROR, TCP ogn data 474554*****8d230d614e1630b7b391360520b4707cee0f4bfc562a61403ddc497b0c119c1b16fb4630640d98c7c3a9b8f2cc5e2331a4da919d9dd2092d5e2ffc3ca104867d1d42fc6ffe90a40128ba0ea47a49f6d7cba5f00c57fa103d29df40e8767362a10449989270f376e1d99ea40388af8652fc5bd16f05bfbc929e043e71f56ff9 from ::ffff:113.200.72.200:39426 via port 34567 by UID 34567<br /><li>2020-10-25 23:26:19 ERROR&nbsp; &nbsp; tcprelay.py:1097 can not parse header when handling connection from ::ffff:113.200.72.200:39426<br /><li>2020-10-25 23:28:33 WARNING&nbsp;&nbsp;auth.py:125 obfs auth: deprecated id, someone replay attack<br /><li>2020-10-25 23:28:33 INFO&nbsp; &nbsp;&nbsp;&nbsp;auth.py:355 auth_sha1_v4: auth fail, data 6f83955f80296e80ff29af00030f7777772e677374617469632e636f6d01bb<br /><li>2020-10-25 23:28:33 WARNING&nbsp;&nbsp;common.py:250 unsupported addrtype 69, maybe wrong password or encryption method<br /><li>2020-10-25 23:28:33 WARNING&nbsp;&nbsp;tcprelay.py:521 Protocol ERROR, TCP ogn data 474554******6c1c9882f6f9a11ddbca85ba29b5e984dbc443d5ed774b4b980b5a4322ef8ff207e0254a156cfcc000b62ca530b0c60aafd2fee43de297272953709fe19e8b1a7d1fe9ef6a95e606b8db8d3604c375105c30f4a163738c2a9948a7c6372783318edab4c94f4d278bae799634a70bf6359a7e5f2baab457b0902c120d179b7931d0d5aee624a2c81184e9 from ::ffff:220.200.165.213:57708 via port 34567 by UID 34567<br /><li>2020-10-25 23:28:33 ERROR&nbsp; &nbsp; tcprelay.py:1097 can not parse header when handling connection from ::ffff:220.200.165.213:57708<br /><li>2020-10-26 00:05:37 WARNING&nbsp;&nbsp;auth.py:131 obfs auth: duplicate id, someone replay attack<br /><li>2020-10-26 00:05:37 INFO&nbsp; &nbsp;&nbsp;&nbsp;auth.py:355 auth_sha1_v4: auth fail, data 3894955f80296e806d2aaf0001acd91a8a01bd<br /><li>2020-10-26 00:05:37 WARNING&nbsp;&nbsp;common.py:250 unsupported addrtype 69, maybe wrong password or encryption method<br /><li>2020-10-26 00:05:37 WARNING&nbsp;&nbsp;tcprelay.py:521 Protocol ERROR, TCP ogn data 474554202f25373925623525386625373725633725633125383525613725663725663025666525326125373825623025333325373125616125306******ead1ae40b356495cb135162ec7d73d645a03abc3b40c37f20194e69098081960ff4e3605a669d9dc0de1279e84755dbcb718adf677cb60206185b53aff3f1a8f3e1c73b6e2aa1be6147d6b720325970a0b3d43947cd6cad67c53e710a0d0b44a0f02d2a564cf7a402cbf1e53cfc94b862ecf34dc5eb1134 from ::ffff:110.177.180.37:48584 via port 34567 by UID 34567<br /><li>2020-10-26 00:05:37 ERROR&nbsp; &nbsp; tcprelay.py:1097 can not parse header when handling connection from ::ffff:110.177.180.37:48584<br /><li>2020-10-26 10:03:03 WARNING&nbsp;&nbsp;common.py:250 unsupported addrtype 69, maybe wrong password or encryption method<br /><li>2020-10-26 10:03:03 WARNING&nbsp;&nbsp;tcprelay.py:521 Protocol ERROR, TCP ogn data 48454144202f20485454502f312e300d0a0d0a from ::ffff:198.144.190.164:35840 via port 34567 by UID 34567<br /><li>2020-10-26 10:03:03 ERROR&nbsp; &nbsp; tcprelay.py:1097 can not parse header when handling connection from ::ffff:198.144.190.164:35840<br /><li>2020-10-26 13:33:10 INFO&nbsp; &nbsp;&nbsp;&nbsp;server.py:48 current process RLIMIT_NOFILE resource: soft 1024 hard 4096<br /><li>2020-10-26 13:33:10 INFO&nbsp; &nbsp;&nbsp;&nbsp;asyncdns.py:287 black_hostname_list init as : []<br /><li>2020-10-26 13:33:10 INFO&nbsp; &nbsp;&nbsp;&nbsp;asyncdns.py:335 dns server: [('8.8.8.8', 53)]<br /><li>2020-10-26 13:33:10 INFO&nbsp; &nbsp;&nbsp;&nbsp;server.py:108 server start with protocol[auth_sha1_v4] password [110110110] method [aes-256-cfb] obfs [http_simple] obfs_param []<br /><li>2020-10-26 13:33:10 INFO&nbsp; &nbsp;&nbsp;&nbsp;server.py:125 starting server at [::]:34567<br /><li>2020-10-26 13:33:10 INFO&nbsp; &nbsp;&nbsp;&nbsp;server.py:145 starting server at 0.0.0.0:34567<br /><li>IPv6 not support<br /><li>started<br /><li>2020-10-26 15:13:55 INFO&nbsp; &nbsp;&nbsp;&nbsp;server.py:48 current process RLIMIT_NOFILE resource: soft 1024 hard 4096<br /><li>2020-10-26 15:13:55 INFO&nbsp; &nbsp;&nbsp;&nbsp;asyncdns.py:287 black_hostname_list init as : []<br /><li>2020-10-26 15:13:55 INFO&nbsp; &nbsp;&nbsp;&nbsp;asyncdns.py:335 dns server: [('8.8.8.8', 53)]<br /><li>2020-10-26 15:13:55 INFO&nbsp; &nbsp;&nbsp;&nbsp;server.py:108 server start with protocol[auth_sha1_v4] password [110110110] method [aes-256-cfb] obfs [http_simple] obfs_param []<br /><li>2020-10-26 15:13:55 INFO&nbsp; &nbsp;&nbsp;&nbsp;server.py:125 starting server at [::]:34567<br /><li>2020-10-26 15:13:55 INFO&nbsp; &nbsp;&nbsp;&nbsp;server.py:145 starting server at 0.0.0.0:34567<br /><li></ol></div><em onclick="copycode($('code_GDg'));">复制代码</em></div>

自己扫下端口不就知道结果了
